### ISSUE TITLE
Wrong ID Returned When executing the OneSignal.viewDevices Method

### ISSUE THREAD

**Issue by eugenedw** [CurrencyFair/OneSignal-Java-SDK#11]
We're attempting to get the playerIds using the specification defined for the RESTful endpoint at https://onesignal.com/api/v1/players?app_id={appId}&limit=300&offset=0

When running with curl, the results come back as expected, for example:
{"id":"a3xxxxx-a80f-4xxd-98xx-c5xxbe7xxxxx","identifier":null,"session_count":2,"language":"en","timezone":-25200,"game_version":"2.8.1","device_os":"9.3","device_type":0,"device_model":"x86_64","ad_id":"7ExxxxxA75-7Axx-4xxD-9F27-5BExxxxxxxxxx","tags":{},"last_active":1472105955,"playtime":0,"amount_spent":0.0,"created_at":1472105504,"invalid_identifier":true,"badge_count":0,"sdk":"011103","test_type":null}

However, when invoking the CurrencyFair method OneSignal.viewDevices(restkey, appId, limit, offset), calling with the same parameters, the "identifier" returned is the player's ios or android token. There is no place on the list of ViewDevicesResponse objects that contains the correct userId/playerId.

**Comment by ericcwcw** [comment]
Hi @eugenedw, you are right that the `id` is missing from the `ViewDevicesResponse`/`ViewDeviceResponse`. However, from onesignal [doc](https://documentation.onesignal.com/reference/add-a-device) where `identifier` is described in details, it refers to the ios/android token.
