### ISSUE TITLE
NotificationRequestBuilder withFilters replaces Operator if called after withFilterOperator

### ISSUE THREAD

**Issue by Grohden** [CurrencyFair/OneSignal-Java-SDK#13]
The current behavior of the `withFilters` is to assign the given param to the filters list, and that causes the `withFilterOperator` to be ignored if called before. eg:

```java
final NotificationRequest notificationRequest = NotificationRequestBuilder
			.aNotificationRequest()
			.withAppId(APP_ID)
			.withHeading("en", NOTIFICATION_TITLE)
			.withFilterOperator(Operator.OR) // filters.add(new Filter(operator))
                        .withFilters(filters) // this.filters = filters; and the above is ignored.
			.withData(data)
			.withContent("en", message)
			.build();
```

My suggestion is to keep the `Operator` in another variable and only add it to the `List` on `build` call.
(if i got it right, the `withFilterOperator` will be applied to all filters)

**Comment by ericcwcw** [comment]
Hi @Grohden, from onesignal [doc](https://documentation.onesignal.com/reference/create-notification#filter-usage), operator needs to be inserted between entries. Would this approach `withFilter(X).withFilterOperator(Operator.OR).withFilter(Y)` fit your use cases? The `withFilters` refers to the `filters` parameter in the [http request](https://documentation.onesignal.com/reference/create-notification#send-based-on-filterstags---create-notification) and expects operators to be included in the array.

**Comment by Grohden** [comment]
@ericwcc Its been like 4 years since I've had to deal with java SDK XD, not sure if it was solved in the meantime, but...

> Would this approach `withFilter(X).withFilterOperator(Operator.OR).withFilter(Y)` fit your use cases?

If I recall, `withFilter(X).withFilterOperator(Operator.OR)` would be totally ignored (since all of their changes would be replaced by `Y`), my point was that this is(was?) kind of implicit behavior and is easy to miss

**Comment by cfechung** [comment]
`withFilter` and `withFilterOperator` are adding filters to the list so `withFilter(Y)` is just adding another filter to it. It is the `withFilters()` (in plural) that will replace those defined earlier. To me, this behaviour is kind of modelling onesignal api's.

**Comment by ericcwcw** [comment]
Hi @Grohden, `withFiler` and `withFilterOperator` are adding filters to the list so `withFilter(Y)` is just appending `Y` to it. It is the `withFilters()` (in plural) that will replace those defined earlier.

**Comment by Grohden** [comment]
oh, right... Ok then:

> Would this approach withFilter(X).withFilterOperator(Operator.OR).withFilter(Y) fit your use cases?

Yes.

I recall that at the time I thought that I could first make a list of filters (no op) and then add a single operator at the end (`[filter, filter, filter, or]`) to say that all filters would be concatenated with that operator (and also because reading `make a notification withFilterOperator OR + withFilters Xs` made sense for me)...

But I see now that the `withFilterOperator` is just a shortcut to the `withFilter` (I would use an overload though: `withFilter(Operator operator)` since operators **are** filters)

Anyway, since no one other than me had problems with it in all these years, I don't think this issue is valid, so I'm gonna close it
