### ISSUE TITLE
No Channel For Android

### ISSUE THREAD

**Issue by QuattroViper** [CurrencyFair/OneSignal-Java-SDK#20]
Is there currently functionality to create android channel from this SDK? 

Because sending from the OneSignal website, the notification becomes a "HeadsUp" popup, but from this SDK, it's just a normal notification. 

The payload that's coming from the OneSignal website contains the following obejct: 
chnl={"dscr":" " , "grp_nm":" " , "grp_id":"OS_GUID" , "id":"OS_GUID" , "nm":" " }.

But the payload from this SDK, the object does not exist. I suspect this is crucial for "HeadsUp" notification. 

I am using Flutter btw.

**Comment by QuattroViper** [comment]
I can just use OneSignal template's ID. That will include the channel object

**Comment by ericzai** [comment]
Hi @QuattroViper , great to know about the workaround using template's ID. Feel free to open another issue if there are further questions.
