### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by calvernaz** [CurrencyFair/OneSignal-Java-SDK#26]
Create release `1.0.12` with the new changes and publish the artifact.

@sriprasanna do you know why snapshots are not being published ?

**Comment by mluis** [comment]
Indeed. Need the latest version.

**Comment by sriprasanna** [comment]
You should see the new release on Maven soon. https://github.com/CurrencyFair/OneSignal-Java-SDK/releases/tag/1.0.12
