### ISSUE TITLE
Release 1.0.12 to Maven Repository

### ISSUE THREAD

**Issue by yakuninv** [CurrencyFair/OneSignal-Java-SDK#29]
Do you have any plans to release version 1.0.12 to https://mvnrepository.com/artifact/com.currencyfair/onesignal ?

Thanks
Sla

**Comment by bavicj** [comment]
+1

**Comment by vikiival** [comment]
@sriprasanna do you have any updates about this issue ?

**Comment by molleafauss** [comment]
Related to #34 , we'll hope to fix it soon(tm)

**Comment by tobamaestro** [comment]
+1

**Comment by molleafauss** [comment]
We managed to release 1.0.14 to nexus central, which includes all previous versions and changes from 1.0.11. 
I see the jar in the nexus management console, and repo.maven.org mirrors seems to hold the jar.
search.maven.org still shows 1.0.11 as latest, but should be updating soon.

Closing this. Wow, just in time for the end of the year... 😕
