### ISSUE TITLE
Release build is broken

### ISSUE THREAD

**Issue by molleafauss** [CurrencyFair/OneSignal-Java-SDK#34]
Need changes to how we release as sems we can't release to the maven central.

**Comment by tobamaestro** [comment]
Any progress?

**Comment by molleafauss** [comment]
We're in touch with the Maven Central as we don't seem to be able to interact with Travis (where the build is hosted).

**Comment by tobamaestro** [comment]
Alright, good to know it's still an ongoing project. Keep up the good work! Thanks.

**Comment by molleafauss** [comment]
We managed to release 1.0.14 to nexus central, which includes all previous versions and changes from 1.0.11. 
I see the jar in the nexus management console, and repo.maven.org mirrors seems to hold the jar (https://repo1.maven.org/maven2/com/currencyfair/onesignal/1.0.14/onesignal-1.0.14.jar), maven should be able to download the dependency.
search.maven.org still shows 1.0.11 as latest, but should be updating soon.
