### ISSUE TITLE
Creating filters

### ISSUE THREAD

**Issue by bart-wh** [CurrencyFair/OneSignal-Java-SDK#9]
Hi,
I'm trying to create notification with Filter.
I think there is a problem with JSON representation of `Operator` field. 

This code
 `
Filter filter = new Filter(Field.TAG, "mykey", Relation.EQUALS, "123", Operator.AND);
NotificationRequestBuilder.aNotificationRequest()
      .withAppId("xxxxxxxxx")
      .withFilter(filter)
      .withContent("en", content)
      .build();
`
produces JSON: 
`[{"key"=>"mykey", "field"=>"tag", "value"=>"123", "operator"=>"AND", "relation"=>"="}]`

However it does not seem to work. 
According to OneSignal Docs, `operator` filed should be a separate object in the list:
`[{"key"=>"mykey", "field"=>"tag", "value"=>"123", "relation"=>"="}, {"operator"=>"AND"}]`

Is it an issue or I'm doing sth wrong?

**Comment by mateusz-bajorek** [comment]
Hi @bszmit, you are right.
I'll make the change to the code shortly, after that you will use filters as such:
```java
NotificationRequestBuilder
    .aNotificationRequest()
    .withAppId("xxxxxxxxx")
    .withFilter(new Filter(Field.TAG, "mykey", Relation.EQUALS, "123"))
    .withFilter(new Filter(Operator.AND))  // or .withFilterOperator(Operator.AND)
    .withFilter(new Filter(Field.TAG, "myotherkey", Relation.EQUALS, "321"))
    .withContent("en", content)
    .build();
```

**Comment by mateusz-bajorek** [comment]
@bszmit version 1.0.9 has been released to maven central, you should be able to use it shortly, after everything gets synchronised between sonatype and central.

**Comment by bart-wh** [comment]
It seems to work now.
Thanks !
